//Base Rust Types
#include "../../../ironoxide-java/cpp/generated/sdk/rust_vec.h"
#include "../../../ironoxide-java/cpp/generated/sdk/rust_vec_i8.h"
#include "../../../ironoxide-java/cpp/generated/sdk/CRustSlicei8.h"
#include "../../../ironoxide-java/cpp/generated/sdk/rust_slice.h"
#include "../../../ironoxide-java/cpp/generated/sdk/rust_option.h"
#include "../../../ironoxide-java/cpp/generated/sdk/rust_result4232mut3232c_voidCRustString.h"
#include "../../../ironoxide-java/cpp/generated/sdk/rust_resultCRustOption4232mut3232c_voidCRustString.h"
#include "../../../ironoxide-java/cpp/generated/sdk/rust_resultCRustForeignVecCRustString.h"
#include "../../../ironoxide-java/cpp/generated/sdk/rust_resultCRustVeci32CRustString.h"

//Base IronOxide Types
#include "../../../ironoxide-java/cpp/generated/sdk/c_PrivateKey.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_EncryptedPrivateKey.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_PublicKey.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_DeviceSigningKeyPair.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_UserId.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_GroupId.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_DeviceId.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_DeviceName.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_UserResult.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_DocumentId.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_DocumentName.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_GroupName.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_SucceededResult.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_FailedResult.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_AssociationType.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_DeviceAddResult.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_DeviceContext.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_NullableBoolean.h"

//Create Opts
#include "../../../ironoxide-java/cpp/generated/sdk/c_GroupCreateOpts.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_UserCreateOpts.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_DeviceCreateOpts.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_DocumentEncryptOpts.h"

#include "../../../ironoxide-java/cpp/generated/sdk/c_UserCreateResult.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_UserDeviceListResult.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_UserDevice.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_UserWithKey.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_UserUpdatePrivateKeyResult.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_GroupUserList.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_GroupCreateResult.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_GroupListResult.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_GroupGetResult.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_GroupMetaResult.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_DocumentListResult.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_DocumentListMeta.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_DocumentMetadataResult.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_DocumentEncryptResult.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_DocumentDecryptResult.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_DocumentEncryptUnmanagedResult.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_UserOrGroupId.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_DocumentDecryptUnmanagedResult.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_GroupAccessEditErr.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_GroupAccessEditResult.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_GroupUpdatePrivateKeyResult.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_DocumentAccessResult.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_Category.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_Sensitivity.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_DataSubject.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_PolicyCachingConfig.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_PolicyGrant.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_Duration.h"

#include "../../../ironoxide-java/cpp/generated/sdk/c_BlindIndexSearch.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_EncryptedBlindIndexSalt.h"

//IronOxide
#include "../../../ironoxide-java/cpp/generated/sdk/c_IronOxideConfig.h"
#include "../../../ironoxide-java/cpp/generated/sdk/c_IronOxide.h"

