//Base Rust Types
#include "rust_vec.h"
#include "rust_vec_i8.h"
#include "CRustSlicei8.h"
#include "rust_slice.h"
#include "rust_option.h"
#include "rust_result4232mut3232c_voidCRustString.h"
#include "rust_resultCRustOption4232mut3232c_voidCRustString.h"
#include "rust_resultCRustForeignVecCRustString.h"
#include "rust_resultCRustVeci32CRustString.h"
#include "rust_slice_mut.h"

//Base IronOxide Types
#include "c_PrivateKey.h"
#include "c_EncryptedPrivateKey.h"
#include "c_PublicKey.h"
#include "c_DeviceSigningKeyPair.h"
#include "c_UserId.h"
#include "c_GroupId.h"
#include "c_DeviceId.h"
#include "c_DeviceName.h"
#include "c_UserResult.h"
#include "c_DocumentId.h"
#include "c_DocumentName.h"
#include "c_GroupName.h"
#include "c_SucceededResult.h"
#include "c_FailedResult.h"
#include "c_AssociationType.h"
#include "c_DeviceAddResult.h"
#include "c_DeviceContext.h"
#include "c_NullableBoolean.h"

//Create Opts
#include "c_GroupCreateOpts.h"
#include "c_UserCreateOpts.h"
#include "c_DeviceCreateOpts.h"
#include "c_DocumentEncryptOpts.h"

#include "c_UserCreateResult.h"
#include "c_UserDeviceListResult.h"
#include "c_UserDevice.h"
#include "c_UserWithKey.h"
#include "c_UserUpdatePrivateKeyResult.h"
#include "c_GroupUserList.h"
#include "c_GroupCreateResult.h"
#include "c_GroupListResult.h"
#include "c_GroupGetResult.h"
#include "c_GroupMetaResult.h"
#include "c_DocumentListResult.h"
#include "c_DocumentListMeta.h"
#include "c_DocumentMetadataResult.h"
#include "c_DocumentEncryptResult.h"
#include "c_DocumentDecryptResult.h"
#include "c_DocumentEncryptUnmanagedResult.h"
#include "c_UserOrGroupId.h"
#include "c_DocumentDecryptUnmanagedResult.h"
#include "c_GroupAccessEditErr.h"
#include "c_GroupAccessEditResult.h"
#include "c_GroupUpdatePrivateKeyResult.h"
#include "c_DocumentAccessResult.h"
#include "c_Category.h"
#include "c_Sensitivity.h"
#include "c_DataSubject.h"
#include "c_PolicyCachingConfig.h"
#include "c_PolicyGrant.h"
#include "c_Duration.h"
#include "c_BlindIndexSearch.h"
#include "c_EncryptedBlindIndexSalt.h"
#include "c_JwtClaims.h"
#include "c_Jwt.h"
#include "c_VisibleUser.h"
#include "c_VisibleGroup.h"
#include "c_GroupAccessErr.h"
#include "c_UserAccessErr.h"

//IronOxide
#include "c_IronOxideConfig.h"
#include "c_IronOxide.h"
