import protocol Foundation.LocalizedError

/// Errors generated by IronOxide SDK operations
public enum IronOxideError: LocalizedError {
    /// Description of the error
    case error(String)
    public var errorDescription: String? {
        switch self {
        case let .error(message):
            return message
        }
    }
}
