#if !canImport(ObjectiveC)
import XCTest

extension UserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UserTests = [
        ("testListDevices", testListDevices),
    ]
}

extension UtilTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UtilTests = [
        ("testIntFromBool", testIntFromBool),
        ("testIsTrue", testIsTrue),
        ("testTimestampToDate", testTimestampToDate),
        ("testUtf8RoundTrip", testUtf8RoundTrip),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(UserTests.__allTests__UserTests),
        testCase(UtilTests.__allTests__UtilTests),
    ]
}
#endif
