name: Docs

on:
  push:
    branches: doc-trigger

jobs:
  build-docs:
    runs-on: macos-10.15
    steps:
      - name: Checkout ironoxide-swig-bindings
        uses: actions/checkout@v2
        with:
          repository: IronCoreLabs/ironoxide-swig-bindings
          path: ironoxide-swig-bindings
      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: ironoxide-swig-bindings/target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
      - name: Cargo build
        run: cargo build -p ironoxide-cpp --release
        working-directory: ironoxide-swig-bindings
      - name: Checkout
        uses: actions/checkout@v2
        with:
          clean: false
      # The following steps move the compiled libironoxide binaries and headers into the proper place in order for them
      # to work with Swift. Currently this library expects the headers/binary to be installed on the system via Homebrew
      # but we only publish the iOS binary to Homebrew, not one for MacOS. Therefore we do these hacks below so the library
      # can find the right files.
      - name: Move libironoxide
        run: mkdir -p .build/x86_64-apple-macosx/debug && cp ironoxide-swig-bindings/target/release/libironoxide.dylib $_
      - name: Move header files
        run: cp -R ironoxide-swig-bindings/cpp/generated/sdk/*.h Sources/libironoxide
      - name: Publish Jazzy Docs
        uses: steven0351/publish-jazzy-docs@v1
        with:
          personal_access_token: ${{ secrets.DEPLOY_TOKEN }}
          args: --module IronOxide
