name: Swift

on:
  push:
    branches: [master, 27-swift-ci]
  pull_request:
    branches: master

jobs:
  build-ironoxide-java:
    strategy:
      matrix:
        target: [ubuntu-18.04, macos-10.15]
        include:
          - target: ubuntu-18.04
            library: libironoxide_shared.so
          - target: macos-10.15
            library: libironoxide_shared.a
    runs-on: ${{ matrix.target }}
    steps:
      - name: Checkout ironoxide-java
        uses: actions/checkout@v2
        with:
          repository: IronCoreLabs/ironoxide-java
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
      - name: Change to staticlib (Mac only)
        run: sed -i -- "s|cdylib|staticlib|g" cpp/Cargo.toml
      - name: Cargo build
        run: cargo build -p ironoxide-cpp
      - name: Zip C headers (Linux only)
        run: |
          cd cpp/generated/sdk
          zip -r c_headers.zip *
        if: matrix.target == 'ubuntu-18.04'
      - name: Upload C headers as artifact (Linux only)
        uses: actions/upload-artifact@v1
        with:
          name: c_headers
          path: cpp/generated/sdk/c_headers.zip
        if: matrix.target == 'ubuntu-18.04'
      - name: Upload shared library
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.host }}-library
          path: target/debug/${{ matrix.library }}

  test-ironoxide-swift:
    needs: build-ironoxide-java
    strategy:
      matrix:
        target: [ubuntu-18.04, macos-10.15]
        include:
          - target: ubuntu-18.04
            library: libironoxide_shared.so
          - target: macos-10.15
            library: libironoxide_shared.a
    runs-on: ${{ matrix.target }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download C headers
        uses: actions/download-artifact@v2
        with:
          name: c_headers
      - name: Unzip C headers
        run: unzip -o c_headers.zip -d c_headers/
      - name: Download shared library
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.host }}-library
      - name: Fix path in "ironoxide.h"
        run: sed -i -- "s|../ironoxide-java/cpp/generated/sdk|c_headers|g" Sources/libironoxide/ironoxide.h
      - name: Build
        run: swift build
      - name: Move libironoxide_shared (Linux)
        run: mv ${{ matrix.library }} .build/x86_64-unknown-linux-gnu/debug
        if: matrix.target == ubuntu-18.04
      - name: Run tests
        run: swift test --enable-test-discovery -v
